version: '3.9'

services:
  postgres:
    container_name: tenkuro-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - tenkuro-postgres_data:/var/lib/postgresql/data
    networks:
      - tenkuro-backend
    ports:
      - '5432:5432'

  redis:
    container_name: tenkuro-redis
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - tenkuro-redis_data:/data
    networks:
      - tenkuro-backend

volumes:
  tenkuro-postgres_data:
  tenkuro-redis_data:

networks:
  tenkuro-backend:
